### PR TITLE
fix: calling parse multiple times now appropriately maintains state (#1137)

### LINKED ISSUE #1137: when in singleton mode, calling parse() multiple times results in undefined behavior
So my situation is that I want to use a required positional argument with some non-required options. To my surprise the positional argument is not picked up as I expected. Here is what the command look like
```bash
$ > node index.js stress-test restock
index.js stress-test <notification>

Some description

Positionals:
  notification  notification type to stress test
                                        [string] [required] [choices: "restock"]

Options:
  --version             Show version number                            [boolean]
  --help                Show help                                      [boolean]
  --amount, -n          amount of notifications to create  [number] [default: 1]
  --environment, --env  environment to conduct stress test in
                                 [choices: "dev", "stg", "pro"] [default: "stg"]

Missing required argument: notification
```

If I try to give an argument that is not part of the argument choice this is what I get:
```bash
$ > node index.js stress-test test
index.js stress-test <notification>

Some description

Positionals:
  notification  notification type to stress test
                                        [string] [required] [choices: "restock"]

Options:
  --version             Show version number                            [boolean]
  --help                Show help                                      [boolean]
  --amount, -n          amount of notifications to create  [number] [default: 1]
  --environment, --env  environment to conduct stress test in
                                 [choices: "dev", "stg", "pro"] [default: "stg"]

Invalid values:
  Argument: notification, Given: "test", Choices: "restock"
```

So obviously the argument is properly picked up. Not sure what is going on here. This is what the command option looks like:

```javascript
   {
      command: 'stress-test <notification>',
      describe: 'Some description',
      builder: (yargs) => {
        return yargs.positional('notification', {
          describe: 'notification type to stress test',
          choices: ['restock'],
          type: 'string'
        }).options({
          amount: {
            default: 1,
            requiresArg: true,
            describe: 'amount of notifications to create',
            alias: 'n',
            number: true
          },
          environment: {
            default: 'stg',
            requresArg: true,
            choices: ['dev','stg','pro'],
            describe: 'environment to conduct stress test in',
            alias: 'env'
          }
        });
      }
   }
```

### PR DESCRIPTION
**Pull request by mleguen**
Extends the freezing/unfreezing mechanism already in place for `parse(args, cb)` to `parse()` (without arguments) to be able to call it several times with the same behavior.

Also corrects the builder function return value handler for it no longer to depend on `yargs.parsed` being set after a call to `parse()` (which is no longer the case after unfreezing).

Closes #1137

### CODE REVIEW

**Comment by bcoe** [comment]
@mleguen I'll definitely have to look at this work closely, years since I touched these bits :smile: 

but this sounds like awesome progress.

File: test/yargs.js [hunk 1]
```diff
@@ -2035,17 +2058,23 @@ describe('yargs dsl tests', () => {
     })
 
     it('allows a defaultDescription to be set', () => {
-      yargs('cmd')
+      const r = checkOutput(() => yargs('cmd --help').wrap(null)
         .command('cmd [heroes...]', 'a command', (yargs) => {
```
Comment (bcoe) [inline test/yargs.js]: I'm a tiny bit afraid of this change, as it seems to potentially be breaking (not a blocker, but might mean this needs to be released in a major).

Is the issue that `yargs.getOptions().defaultDescription` used to maintain state from the last command to execute, and now with this fix the freezing behavior reverts it to an initial state?

Comment (mleguen) [reply test/yargs.js]: That's exactly the point.

And the test I corrected was using the command state leaking to the parent yargs to perform its checks.

So the fix does not break any documented use case... but it could break some programs relying on that leaking command state, as our own test did.

So... major release or not?

Comment (bcoe) [reply test/yargs.js]: I say major, not a big deal, we're at 13.x already :stuck_out_tongue:

With tools like renovate bot and greenkeeper, I'd rather stay on the side of caution ... it lets us catch major bugs sooner.
