### PR TITLE
fix: align browser shim version

### LINKED ISSUE #1981: Browser version does not work (17.0.1)
The browser version of yargs works fine for `16.0.0-alpha.3`, but for latest available version on unpkg it not working.
This is easy to test, open [jsfiddle from yargs docs](https://jsfiddle.net/bencoe/m9fv2oet/3/).
And replace this:
```js
import { Yargs } from 'https://unpkg.com/yargs@16.0.0-alpha.3/browser.mjs';
```
To this
```js
import Yargs from 'https://unpkg.com/yargs@17.0.1/browser.mjs';
```
Then save and play with yargs, you will see a lot of errors, like this:

```
alert --help
---
Uncaught TypeError: __classPrivateFieldGet(...).Parser.looksLikeNumber is not a function
    parsePositionalNumbers https://unpkg.com/yargs@17.0.1/build/lib/yargs-factory.js:1045
    postProcess https://unpkg.com/yargs@17.0.1/build/lib/yargs-factory.js:1204
    runYargsParserAndExecuteCommands https://unpkg.com/yargs@17.0.1/build/lib/yargs-factory.js:1336
    parse https://unpkg.com/yargs@17.0.1/build/lib/yargs-factory.js:675
    <anonymous> https://fiddle.jshell.net/_display/?editor_console=true:143
    EventListener.handleEvent* https://fiddle.jshell.net/_display/?editor_console=true:141
yargs-factory.js:1045:62
```

```
alert
---
Uncaught TypeError: __classPrivateFieldGet(...).Parser.looksLikeNumber is not a function
    parsePositionalNumbers https://unpkg.com/yargs@17.0.1/build/lib/yargs-factory.js:1045
    postProcess https://unpkg.com/yargs@17.0.1/build/lib/yargs-factory.js:1204
    runYargsParserAndExecuteCommands https://unpkg.com/yargs@17.0.1/build/lib/yargs-factory.js:1420
    parse https://unpkg.com/yargs@17.0.1/build/lib/yargs-factory.js:675
    <anonymous> https://fiddle.jshell.net/_display/?editor_console=true:143
    EventListener.handleEvent* https://fiddle.jshell.net/_display/?editor_console=true:141
yargs-factory.js:1045:62
```

```
clear
---
Uncaught TypeError: __classPrivateFieldGet(...).Parser.looksLikeNumber is not a function
    parsePositionalNumbers https://unpkg.com/yargs@17.0.1/build/lib/yargs-factory.js:1045
    postProcess https://unpkg.com/yargs@17.0.1/build/lib/yargs-factory.js:1204
    runYargsParserAndExecuteCommands https://unpkg.com/yargs@17.0.1/build/lib/yargs-factory.js:1420
    parse https://unpkg.com/yargs@17.0.1/build/lib/yargs-factory.js:675
    <anonymous> https://fiddle.jshell.net/_display/?editor_console=true:143
    EventListener.handleEvent* https://fiddle.jshell.net/_display/?editor_console=true:141
yargs-factory.js:1045:62
```

Is browser part will be mantained in future, I want to use it but not sure is it ready for production.

### PR DESCRIPTION
**Pull request by nomyfan**
This PR can also resolve #1981

### CODE REVIEW

**Comment by shadowspawn** [comment]
Oh drat, another stale hand-coded dependency outside `package.json` like #2306 ! I sense the need for a checklist... 😅 

I'll take a more careful look, but my expectation is we want this. Thanks.

**Review by shadowspawn — APPROVED** [review]
LGTM

(I checked visually and checked dependency versions. Did not check runtime.)

**Comment by nomyfan** [comment]
Thank you for reviewing. Any release plan for this?

**Comment by shadowspawn** [comment]
> Any release plan for this?

Short version: no.

(Is this a blocker for something you are doing, or were you just wondering?)

**Comment by nomyfan** [comment]
I use yargs in my web project which is crashed caused by this. I had used [pnpm patch](https://pnpm.io/cli/patch) to fix it as a workaround so it's not so urgent for me. 
It would be nice to see the fix released in the coming version so that I can remove that patch.😃

File: lib/platform-shims/browser.mjs [hunk 1]
```diff
@@ -1,8 +1,8 @@
 /* eslint-disable no-unused-vars */
 'use strict';
 
-import cliui from 'https://unpkg.com/cliui@7.0.1/index.mjs'; // eslint-disable-line
-import Parser from 'https://unpkg.com/yargs-parser@19.0.0/browser.js'; // eslint-disable-line
+import cliui from 'https://unpkg.com/cliui@8.0.1/index.mjs'; // eslint-disable-line
```
Comment (bcoe) [inline lib/platform-shims/browser.mjs:4]:
```suggestion
import cliui from 'https://unpkg.com/cliui@8.0.1/index.mjs'; // eslint-disable-line  {x-release-please-version}
```

File: lib/platform-shims/browser.mjs [hunk 2]
```diff
@@ -1,8 +1,8 @@
...
+import Parser from 'https://unpkg.com/yargs-parser@21.1.1/browser.js'; // eslint-disable-line
```
Comment (bcoe) [inline lib/platform-shims/browser.mjs:5]:
```suggestion
import Parser from 'https://unpkg.com/yargs-parser@21.1.1/browser.js'; // eslint-disable-line  {x-release-please-version}
```
