### PR TITLE
fix: we shouldn't output help if we've printed a prior help-like message

### LINKED ISSUE #822: recommended command used in conjunction with --help prints twice
```slackboard user <subcommand|help>

Commands:
  update-email <name> <email>           change email to new address for a user
  update-resource <name> <key> <value>  change resource attribute for user
  get <name>                            get user

Options:
  --help  Show help                                                                        [boolean]

Did you mean get?
/usr/bin/nodejs bin/slackboard user <subcommand|help>

Commands:
  update-email <name> <email>           change email to new address for a user
  update-resource <name> <key> <value>  change resource attribute for user
  get <name>                            get user

Options:
  --help  Show help                                                                        [boolean]```

### PR DESCRIPTION
**Pull request by bcoe**
we were accidentally printing the help text twice, if recommendations were made and `exit = false`.

```bash
Commands:
  goat

Options:
  --help  Show help                                                                        [boolean]

Did you mean goat?
Commands:
  goat

Options:
  --help  Show help                                                                        [boolean]
```

Let's not do this, it looks weird!

fixes #822

### CODE REVIEW

File: test/yargs.js [hunk 1]
```diff
@@ -339,6 +339,20 @@ describe('yargs dsl tests', function () {
...
     })
 
+    // see: https://github.com/yargs/yargs/issues/822
+    it('does not print help message if recommendation has been made', function (done) {
+      const parser = yargs()
+        .command('goat')
+        .help()
+        .recommendCommands()
+
+      parser.parse('boat help', {}, function (_err, argv, output) {
```
Comment (JaKXz) [inline test/yargs.js]: It might be redundant, but shouldn't we check that error is null/falsy here? and shouldn't it be `_argv` since we're not using that arg?

Comment (bcoe) [inline test/yargs.js]: @JaKXz 👍 done.
