### PR TITLE
fix(commandDir): make dir relative to caller instead of require.main.filename

### LINKED ISSUE #529: .commandDir(dir) does not work when the yargs definition script is `require`-ed from other file
While I'm building a tool with `.commandDir(dir)`, an error occured when I require `lib/cli.js` and execute `bin/tool.js`.

`node lib/cli.js` works properly.

Directory tree:
```
.
├── bin
│   └── tool.js
├── lib
│   ├── cli.js
│   └── commands
│       └── foo.js
└── package.json

```

bin/tool.js:
```
#!/usr/bin/env node
require('../lib/cli.js');
```

lib/cli.js:
```
'use strict';
require('yargs')
.commandDir('commands')
.argv;
```

lib/commands/foo.js:
```
'use strict';
exports.command = 'foo';
exports.describe = 'description';
exports.builder = {};
exports.handler = function (argv) { console.log('foo') };

```

The error message is:
```
fs.js:945
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOENT: no such file or directory, scandir '/Users/popkirby/Documents/yargs-bug/bin/commands'
    at Error (native)
    at Object.fs.readdirSync (fs.js:945:18)
    at requireDirectory (/Users/popkirby/Documents/yargs-bug/node_modules/require-directory/index.js:59:6)
    at Object.self.addDirectory (/Users/popkirby/Documents/yargs-bug/node_modules/yargs/lib/command.js:72:5)
    at Object.Yargs.self.commandDir (/Users/popkirby/Documents/yargs-bug/node_modules/yargs/yargs.js:211:13)
    at Object.<anonymous> (/Users/popkirby/Documents/yargs-bug/lib/cli.js:4:2)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```

### PR DESCRIPTION
**Pull request by nexdrew**
Pull in [`get-caller-file`](https://github.com/stefanpenner/get-caller-file) to always interpret the directory given to `.commandDir()` as relative to the caller. This actually helps simplify the logic a good bit since I no longer need to keep track of a command-to-dir mapping between calls.

The `require` is deliberately lazy, so we only load the dependency if `.commandDir()` is called.

There are a few different packages that provide the "get filename of caller" functionality, but I chose `get-caller-file` because it was the only one that already had passing tests for the range of Node we need and includes Windows tests ([`caller`](https://github.com/totherik/caller) seems to be popular but is lacking the fuller range of testing, and [`caller-path` seems to be broken on Node 4+](https://github.com/sindresorhus/caller-path/issues/1)). An added benefit is that `get-caller-file` also seems to be the smallest and only pulls in one dependency.

Fixes #529.

### CODE REVIEW

File: lib/command.js [hunk 1]
```diff
@@ -62,14 +60,11 @@ module.exports = function (yargs, usage, validation) {
         if (~context.files.indexOf(joined)) return visited
         // keep track of visited files in context.files
         context.files.push(joined)
-        // map "command path" to the directory path it came from
-        // so that dir can be relative in the API
-        context.dirs[context.commands.concat(parseCommand(visited.command || commandFromFilename(filename)).cmd).join('|')] = dir
```
Comment (bcoe) [inline lib/command.js]: I love how much this simplifies things; except for the fact that yargs' documentation is terrifyingly verbose at this point, I'm really feeling like the command functionality is knocking it out of the park -- phew, that was hard work wasn't it.

**Comment by bcoe** [comment]
love it :shipit:
